
package deployment.model;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.6-1b01 Generated
 * source version: 2.2
 * 
 */
@WebService(name = "StockQuoteTimeLapseServicePortType", targetNamespace = "http://StockQuoteService")
@XmlSeeAlso({ ObjectFactory.class })
public interface StockQuoteTimeLapseServicePortType {

	/**
	 * 
	 * @param symbol
	 * @return returns java.util.List<java.lang.String>
	 */
	@WebMethod(action = "urn:getStockQuote")
	@WebResult(targetNamespace = "http://StockQuoteService")
	@RequestWrapper(localName = "getStockQuote", targetNamespace = "http://StockQuoteService", className = "stockstage2autogenerated.GetStockQuote")
	@ResponseWrapper(localName = "getStockQuoteResponse", targetNamespace = "http://StockQuoteService", className = "stockstage2autogenerated.GetStockQuoteResponse")
	public List<String> getStockQuote(
			@WebParam(name = "symbol", targetNamespace = "http://StockQuoteService") String symbol);

	/**
	 * 
	 * @return returns stockstage2autogenerated.GetSymbolsResponse
	 */
	@WebMethod(action = "urn:getSymbols")
	@WebResult(name = "getSymbolsResponse", targetNamespace = "http://StockQuoteService", partName = "parameters")
	@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
	public GetSymbolsResponse getSymbols();

	/**
	 * 
	 * @return returns stockstage2autogenerated.GetFieldNamesResponse
	 */
	@WebMethod(action = "urn:getFieldNames")
	@WebResult(name = "getFieldNamesResponse", targetNamespace = "http://StockQuoteService", partName = "parameters")
	@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
	public GetFieldNamesResponse getFieldNames();

}
